### ISSUE TITLE
Project check

### ISSUE THREAD

**Issue by kme012** [Bucknell-Biol364/Biology208tutorial#11]
https://github.com/Bucknell-Biol364/Biology208tutorial/blob/9fef1188104ff5f2807250133597440683005487/Biol_208_Tutorial.Rmd#L1

@mwm021 
Hey Matt, could you look this over for us? Make sure you have the practice demography data (the excel file) downloaded too. Thanks!

**Comment by mwm021** [comment]
Here are a few things I suggest editing:

1. Line 28. Instead of starting with "Datasets" I would suggest you say "The Datasets package" to differentiate it from when you say "access the datasets" later in that line.
2. Before generating a hypothesis, I would suggest adding a sentence that encourages the students to look at the dataset and think of possible hypotheses they could test using the data (Line 38). Also maybe tell them that they can view the subsetted data in the "Environment" tab in the top-right window.
3. Line 49: I would suggest adding a note after this code chunk that tells them that they should notice that the petal length is not normally distributed and suggest options they have to make it appear more normal.
4. Line 57: This seems unnecessary to me, I would just stick with the table. But if the bar graph is required for the analysis, then I would go ahead and keep it there. 
5. I would put the shapiro-wilk test after the eda chunk because they are related to each other. Plus you want your analysis and visualization to be separate. (Line 80)
6. Line 85: See my note for Line 49. It would make sense to move this up as well.
7. Line 97: Nice graph!
8. Line 108: Maybe explain what a non-parametric test is? I don't think everyone would know what this means.
9. Line 116: Nice explanation of the relationship! I would suggest making the line that tells them to form their own hypothesis its own line. I could easily imagine someone rushing through lab reading the explanation of the relationship between the variables and totally glossing over the instructions.
10. Line 122: I like the use of comments in your code chunks, I would definitely suggest adding more comments to the first part.
11. Line 147: I got an error when running this line of code. It says "Error in int_abline(a = a, b = b, h = h, v = v, untf = untf, ...) : plot.new has not been called yet". Maybe the code chunk has to be run all at once for this to work rather than line-by-line?
12. Line 162: I would explain that there are two parts to making this (calculations, then visualization). I was not sure if the first chunk did what it was supposed to because I was expecting it to make the curve.
13. Line 186: See my note for Line 116. I think it would be helpful to use something like this there so that the assignment is super obvious to them.
14. Line 275: I would add a note that says the code chunk has to be run all at the same time (using the green arrow on the right). I ran it line-by-line the first time and I got an error on one of the lines, but then when I ran it all together it worked fine.
15. I really like the way that part 3 was made. I like that you don't just give them the code, but that you take the time to explain what R is doing with each part. I would use this approach more throughout!

Overall it's very well done! The code all works as expected, so the only thing I would suggest you work on is some of the formatting and explanation stuff.

**Comment by mnr006** [comment]
Thanks for all these suggestions @mwm021 they were super helpful!!
